<?php
/**
 * @file
 * General hook implementations.
 */

/**
 * Implements hook_module_implements_alter().
 *
 * We replace Islandora's access implementations with our own.
 */
function islandora_access_override_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'islandora_datastream_access' && isset($implementations['islandora'])) {
    unset($implementations['islandora']);
  }
  elseif ($hook == 'islandora_object_access' && isset($implementations['islandora'])) {
    unset($implementations['islandora']);
  }
}

/**
 * Implements hook_islandora_object_access().
 */
function islandora_access_override_islandora_object_access($op, $object, $user) {
  module_load_include('inc', 'islandora_access_override', 'includes/utilities');

  $result = _islandora_access_override_handle($op, $object, $user);

  return $result === NULL ?
    islandora_islandora_object_access($op, $object, $user) :
    $result;
}

/**
 * Implements hook_islandora_datastream_access().
 */
function islandora_access_override_islandora_datastream_access($op, $datastream, $user) {
  module_load_include('inc', 'islandora_access_override', 'includes/utilities');

  $result = _islandora_access_override_handle($op, $datastream, $user);

  return $result === NULL ?
    islandora_islandora_datastream_access($op, $datastream, $user) :
    $result;
}
