<?php

/**
 * @file
 * Module entry hooks.
 */

// Permissions.
const ISLANDORA_OWNER_PERMISSIONS_EDIT_METADATA = 'islandora owner edit metadata';
const ISLANDORA_OWNER_PERMISSIONS_REPLACE_DATASTREAMS = 'islandora owner replace datastreams';
const ISLANDORA_OWNER_PERMISSIONS_CREATE_DATASTREAMS = 'islandora owner create datastreams';
const ISLANDORA_OWNER_PERMISSIONS_REMOVE_OBJECTS = 'islandora owner remove objects';
const ISLANDORA_OWNER_PERMISSIONS_MANAGE_OBJECT_PROPERTIES = 'islandora owner manage object properties';
const ISLANDORA_OWNER_PERMISSIONS_REVERT_DATASTREAMS = 'islandora owner revert datastreams';
const ISLANDORA_OWNER_PERMISSIONS_REGENERATE_DERIVATIVES = 'islandora owner regenerate derivatives';

/**
 * Implements hook_permission().
 */
function islandora_owner_permissions_permission() {
  return array(
    ISLANDORA_OWNER_PERMISSIONS_EDIT_METADATA => array(
      'title' => t('Edit Metadata on Owned Objects'),
      'description' => t('Allows a user to edit metadata on their owned objects.'),
    ),
    ISLANDORA_OWNER_PERMISSIONS_REPLACE_DATASTREAMS => array(
      'title' => t('Replace Datastreams on Owned Objects'),
      'description' => t('Allows a user to replace datastreams on their owned objects.'),
    ),
    ISLANDORA_OWNER_PERMISSIONS_CREATE_DATASTREAMS => array(
      'title' => t('Create Datastreams on Owned Objects'),
      'description' => t('Allows a user to create datastreams on their owned objects.'),
    ),
    ISLANDORA_OWNER_PERMISSIONS_REMOVE_OBJECTS => array(
      'title' => t('Remove Owned Objects'),
      'description' => t('Allows a user to purge their owned objects.'),
    ),
    ISLANDORA_OWNER_PERMISSIONS_MANAGE_OBJECT_PROPERTIES => array(
      'title' => t('Manage Owned Objects Properties'),
      'description' => t('Allows a user to manage the properties of their owned objects.'),
    ),
    ISLANDORA_OWNER_PERMISSIONS_REVERT_DATASTREAMS => array(
      'title' => t('Revert Datastreams on Owned Objects'),
      'description' => t('Allows a user to revert datastreams on their owned objects.'),
    ),
    ISLANDORA_OWNER_PERMISSIONS_REGENERATE_DERIVATIVES => array(
      'title' => t('Regenerate Derivatives on Owned Objects'),
      'description' => t('Allows a user to regenerate derivatives on their owned objects.'),
    ),
  );
}

/**
 * Implements hook_islandora_access_override_object_handlers().
 */
function islandora_owner_permissions_islandora_access_override_object_handlers() {
  module_load_include('inc', 'islandora_owner_permissions', 'includes/utilities');
  $perm_map = islandora_owner_permissions_permission_map();

  $handlers = array();

  $mod_path = drupal_get_path('module', 'islandora_owner_permissions');

  foreach ($perm_map as $perm => $mapped) {
    $handlers[$perm][] = array(
      'callable' => 'islandora_ownership_permissions_test_object',
      'file' => "$mod_path/includes/callbacks.inc",
    );
  }

  return $handlers;
}

/**
 * Implements hook_islandora_access_override_datastream_handlers().
 */
function islandora_owner_permissions_islandora_access_override_datastream_handlers() {
  module_load_include('inc', 'islandora_owner_permissions', 'includes/utilities');
  $perm_map = islandora_owner_permissions_permission_map();

  $handlers = array();

  $mod_path = drupal_get_path('module', 'islandora_owner_permissions');

  $proxy = function ($op, AbstractDatastream $datastream, $user) {
    return islandora_ownership_permissions_test_object($op, $datastream->parent, $user);
  };

  foreach ($perm_map as $perm => $mapped) {
    $handlers[$perm][] = array(
      'callable' => $proxy,
      'file' => "$mod_path/includes/callbacks.inc",
    );
  }

  return $handlers;
}
